Add Emacs/CIDER note
tengstrand/lein-polylith pull request #19
Opened 2018-11-12 11:07 UTC by JAremko

https://github.com/tengstrand/lein-polylith/issues/15 was fixes in the Cider sub-package[[see this discussion]( https://github.com/vspinu/sesman/pull/13)]. So Polylith should now work fine with [Emacs/CIDER](https://github.com/clojure-emacs/cider) with a bit of Emacs configs tweaking.

2018-11-12 12:19 UTC, furkan3ayraktar requested changes
Thanks for creating this PR! I've added my comments, if you can fix them, I would love to merge this ASAP.

2018-11-12 12:19 UTC, furkan3ayraktar commented on readme.md
> +Note: If you use [Emacs/CIDER](https://github.com/clojure-emacs/cider) you should set `vc-follow-symlinks` to `nil` and ensure that `find-file-visit-truename` is `nil`. It can be done with [per-direc
I think it worths to add a title under Development section for this since it's quite important for people using Emacs/CIDER. Maybe these changes would be sufficient, what do you think?

```suggestion
#### Emacs/CIDER Support

If you use [Emacs/CIDER](https://github.com/clojure-emacs/cider) you should set `vc-follow-symlinks` to `nil` and ensure that `find-file-visit-truename` is `nil`. It can be done with [per-directory local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) - just create `.dir-locals.el` file in the *workspace root* directory with this content:
```

2018-11-12 12:19 UTC, furkan3ayraktar commented on readme.md
> +
Also here we can share a link to the original issue in Emacs/CIDER repository, if people what to know why this is necessary.

```suggestion

To see why this is necessary, please check [this issue](https://github.com/clojure-emacs/cider/issues/2505).

```

2018-11-12 12:29 UTC, JAremko commented
@furkan3ayraktar  Should I squash ?

2018-11-12 21:55 UTC, furkan3ayraktar approved these changes

2018-11-12 21:56 UTC, furkan3ayraktar commented
> @furkan3ayraktar Should I squash ?

No need, I'll squash when I merge this.

2018-11-12 21:57 UTC, merged

2018-11-15 07:27 UTC, Misophistful commented
@JAremko I just wanted to say thank you for all your work on this issue. Getting Polylith working in Emacs is a huge deal.